### ISSUE TITLE
Lore and display name store not work in some plugins

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/luckyblocks-sf#31]
## Description (Required)

Lore and display name store not work in some plugins.
It does not work if the plugin stores them in a yml file. It works with all other Slimefun items, only Lucky Blocks data store not work.
Maybe the Lucky Block plugin encoding problem?

## Steps to reproduce the Issue (Required)

1. Place Shopkeepers plugin shop, or sell on Crazy Auctions plugin.
2. Restart server.

<img width="579" alt="Capture" src="https://user-images.githubusercontent.com/8324198/96239452-00f25e80-0fa0-11eb-8eae-a5eb8477fa01.PNG">

```
    Item:
      ==: org.bukkit.inventory.ItemStack
      v: 2580
      type: PLAYER_HEAD
      meta:
        ==: ItemMeta
        meta-type: SKULL
        display-name: Very lucky Block
        lore:
        - 'ยง7Luck: ยงa+80'
        internal: H4sIAAAAAAAAAE2PQW6CQBiF/zY2odMue40moIIxrQsjJA6BoQiiw05hDIwzaBC09Apd9gxduOiup+gduum+dyjLLl6+vHxv8xAAgttgWwvxVO42uWAKdMhKMkCT4H6yK5mTrxGgVu5ZWeXscA1KxZ6rumQHBAAXClxFK1Ez+GSNrcbLTE2XtkgabLQ9DFThYb4f4CJq1hNsYNn66dhwmuG/rV6tFrqgPTuLC79ey0h1ejPBpjMtkfMj5SQnL9aJ8nGf8nnjdu2chqmIpZ25ZsoJxzqV1skztxpd+F03tBoi/TZun0hbUN7SnHddk2RemKgujzkutOHGH40AbuASp+2Rzvf7w+vX3ePb+eM8+Pn1NIA/YDTwCB0BAAA=
        PublicBukkitValues:
          slimefun:slimefun_item: LUCKY_BLOCK_LUCKY
        skull-owner: CS-CoreLib
```

## Expected behavior (Required)

Lore and display name store works in all plugins as with Slimefun items.

## Server Log / Error Report

No error report.

## Environment (Required)

[11:11:23 INFO]: This Server uses the following setup of Slimefun:
[11:11:23 INFO]: Paper v1_16_R2
[11:11:23 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[11:11:23 INFO]: Slimefun vDEV - 722 (git e18c7cb2)
[11:11:23 INFO]: Metrics build: #17
[11:11:23 INFO]:
[11:11:23 INFO]: Installed Addons: (1)
[11:11:23 INFO]:  SlimefunLuckyBlocks vDEV - 29 (git db79cb7c)
