### ISSUE TITLE
bow enchants

### ISSUE THREAD

**Issue by 100petr** [TheBusyBiscuit/luckyblocks-sf#38]
## Description (Required)

Enchants for bow in custom surprise doesn't work
## Steps to reproduce the Issue (Required)

Create custom surprise bow with enchants
Example:
```yaml  
  ExampleSurprise21:
    enabled: true
    lucklevel: LUCKY
    items:
      '1':
        type: BOW
        amount: 1
        displayname: '&e&lEnchanted Bow2'
        lore:
        - '&7Pro Lucky Bow to zkus znovu..'
        enchants:
        - UNBREAKING:4
```       
## Expected behavior (Required)

There will be functional enchants on the bow
## Server Log / Error Report

Error: `[15:54:18 WARN]: [SlimefunLuckyBlocks] Could not set "UNBREAKING" enchant for custom surprise "ExampleSurprise21"`
## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/108081600-6d29bf80-7071-11eb-9cdc-5f53bb5ea136.png)
